# config/packages/nelmio_cors.yaml
nelmio_cors:
    paths:
        '^/': ~
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['*']
