build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  tags:
    - demojob

phpcp-job:
  stage: test
  script:
    - apt-get update && apt-get install -y php-pear
    - pear install PHP_CodeSniffer
    - phpcs /builds/nbentaarit/demo-app-backend/backend/src/Controller/CocktailController.php
  tags:
    - demojob

test-job:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20
  tags:
    - demojob
